### ISSUE TITLE
最新バージョンではないMisskeyのフォークのテストが失敗するようになっている

### ISSUE THREAD

**Issue by u1-liquid** [misskey-dev/assets#6]
テストで参照していたファイルが d32911a で移動されてしまい旧バージョンの全てのMisskeyのテストが失敗しています。

**Comment by kakkokari-gtyih** [comment]
7ad169c4a697e2c1dfff3f43844ff45b169fc126 （一つ前）を明示的に参照して対応できませんか？

**Comment by syuilo** [comment]
バージョン更新してもらえば良さそう

**Comment by u1-liquid** [comment]
更新するとか修正すれば直るのは直りますが…
全ての過去のソースコードのテストが使い物にならなくなっているということを重く見てほしいですね

**Comment by syuilo** [comment]
過去のテストを現在になって実行することは想定していないわね

**Comment by u1-liquid** [comment]
そんなに過去のテストでもないし1.2kの全てのmisskeyのフォークが常にdevelopを追従できるわけではないということをわかってほしい

**Comment by syuilo** [comment]
- Misskeyはフォークの面倒までは見れない(そこまでの余裕がない)
- misskey-dev/misskeyをフォークするならmisskey-dev/assetsも同様にフォークしてもらった方が良さそう

**Comment by syuilo** [comment]
> Misskeyはフォークの面倒までは見れない

READMEとかに書いとくべきかしら

**Comment by u1-liquid** [comment]
「fork向けの変更点とか発行してくれ」など「面倒」をみてほしいということではない
こういうテストに使われているリソースの変更に気を付けてほしい（すくなくとも時間をおいて消すなどをしてほしい）ということです

**Comment by anatawa12** [comment]
そもそもなのですがこれは「勝手に壊れた」という主張でしょうか？

git submoduleを正しく運用していればsubmoduleでcheckoutされるコミットは固定されるので勝手に壊れることはなく、更新したら壊れたということたまと思うのですが間違いないですか？

**Comment by riku6460** [comment]
タイムラインのテストで main を参照しているため submodule 関係なく勝手に壊れますね (main ではなくコミットを指定していれば防げました)

例: https://github.com/misskey-dev/misskey/blob/379079ee42355ae1b1982bc092e06e863a901d09/packages/backend/test/e2e/timelines.ts#L368-L369

**Comment by kakkokari-gtyih** [comment]
とりあえずtestで参照されてるファイルだけ直下に置きなおすか

**Comment by tamaina** [comment]
> タイムラインのテストで main を参照しているため submodule 関係なく勝手に壊れますね (main ではなくコミットを指定していれば防げました)

それならテストをコミットハッシュに書き換えれば済む話かなと…

**Comment by tamaina** [comment]
raw.githubusercontent.comを指定するなりする時はブランチではなくコミットハッシュやタグを参照すべきではあるとは思った

（それはそうと過去のソースコードのテストが動かないと言われても対応しきれないわけですが……）

**Comment by riku6460** [comment]
> > タイムラインのテストで main を参照しているため submodule 関係なく勝手に壊れますね (main ではなくコミットを指定していれば防げました)
> 
> それならテストをコミットハッシュに書き換えれば済む話かなと…

個人的には、もう壊れてしまったものは仕方がないので、旧バージョンについてはそれで良い気はします。
現行のバージョンについては、次の破壊に備えてコミットを指定すると良いのではと思っていますが、どうでしょう。

**Comment by kakkokari-gtyih** [comment]
> 次の破壊に備えてコミットを指定すると良いのでは
そうします

（旧バージョンはとりあえず #7 をマージすれば何とかなるはず）
