### ISSUE TITLE
アセットのライセンスがmisskey-hubとREADMEで異なっている

### ISSUE THREAD

**Issue by mkizka** [misskey-dev/assets#8]
misskey-hubに記載されているライセンスとREADMEに記載のライセンスが異なっているようです。どちらかが正しいか教えて頂きたいです。

> アセットは、CC BY-NC-SAのライセンスの下で自由にお使いいただけます🎉
> https://misskey-hub.net/ja/brand-assets/

> publicディレクトリ内にあるファイルは、[CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/) のライセンスの下でどなたでも自由にお使いいただけます。
> https://github.com/misskey-dev/assets/blob/2886fd4bdb3ed7e94729d95193b9d2466865c9de/README.md

**Comment by kakkokari-gtyih** [comment]
記載ミスでした。[CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)で正しいです
（Misskey Hubを修正しました）
