### ISSUE TITLE
icon.png及びmisskey.svgのライセンスがmisskey-hubの記載と矛盾している

### ISSUE THREAD

**Issue by KisaragiEffective** [misskey-dev/assets#9]
[misskey-hub側](https://github.com/misskey-dev/misskey-hub/blob/7071f63a1c80ee35c71f0fd8a6d8722c118c7574/src/appendix/assets.md?plain=1#L9)ではCC BY-NC-SA 4.0ですが、このレポジトリではCC BY-SA 4.0となっているように見受けられます。
利用するに当たって、どちらを参照したら良いのでしょうか？

**Comment by KisaragiEffective** [comment]
cc @kakkokari-gtyih @syuilo

**Comment by kakkokari-gtyih** [comment]
記載ミスでした。[CC BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/)で正しいです
（[現行Misskey Hub](https://misskey-hub.net/ja/brand-assets/)ではすでに修正済み）

duplicate of #8
